# Generated by Django 3.0.7 on 2020-06-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face',
            field=models.ImageField(blank=True, upload_to='students_face/'),
        ),
    ]
